name: Sort uBlacklist.txt

on:
  push:
    paths:
      - "uBlacklist.txt"

jobs:
  sort:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run sorting script directly
        run: |
          python - <<'EOF'
          file_path = "uBlacklist.txt"

          # ファイル読み込み
          with open(file_path, "r", encoding="utf-8") as file:
              lines = file.readlines()

          # 重複削除＋アルファベット順
          unique_sorted_lines = sorted(set(line.strip() for line in lines if line.strip()))

          # 上書き保存
          with open(file_path, "w", encoding="utf-8") as file:
              file.write("\n".join(unique_sorted_lines) + "\n")

          print("重複を削除し、アルファベット順に並べ替えました:", file_path)
          EOF

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add uBlacklist.txt
          git diff --cached --quiet || git commit -m "Auto-sort uBlacklist.txt"
          git push
